//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Humanizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DateTimeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateTimeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Humanizer.Resources.DateTimeResources", typeof(DateTimeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siècle.
        /// </summary>
        public static string Century {
            get {
                return ResourceManager.GetString("Century", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décennie.
        /// </summary>
        public static string Decade {
            get {
                return ResourceManager.GetString("Decade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # jour.
        /// </summary>
        public static string DurationDay {
            get {
                return ResourceManager.GetString("DurationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # jours.
        /// </summary>
        public static string DurationDayPlural {
            get {
                return ResourceManager.GetString("DurationDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 jour.
        /// </summary>
        public static string DurationDayZero {
            get {
                return ResourceManager.GetString("DurationDayZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # heure.
        /// </summary>
        public static string DurationHour {
            get {
                return ResourceManager.GetString("DurationHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # heures.
        /// </summary>
        public static string DurationHourPlural {
            get {
                return ResourceManager.GetString("DurationHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 heure.
        /// </summary>
        public static string DurationHourZero {
            get {
                return ResourceManager.GetString("DurationHourZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # milliseconde.
        /// </summary>
        public static string DurationMillisecond {
            get {
                return ResourceManager.GetString("DurationMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # millisecondes.
        /// </summary>
        public static string DurationMillisecondPlural {
            get {
                return ResourceManager.GetString("DurationMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 milliseconde.
        /// </summary>
        public static string DurationMillisecondZero {
            get {
                return ResourceManager.GetString("DurationMillisecondZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # minute.
        /// </summary>
        public static string DurationMinute {
            get {
                return ResourceManager.GetString("DurationMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # minutes.
        /// </summary>
        public static string DurationMinutePlural {
            get {
                return ResourceManager.GetString("DurationMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 minutes.
        /// </summary>
        public static string DurationMinuteZero {
            get {
                return ResourceManager.GetString("DurationMinuteZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # mois.
        /// </summary>
        public static string DurationMonth {
            get {
                return ResourceManager.GetString("DurationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # mois.
        /// </summary>
        public static string DurationMonthPlural {
            get {
                return ResourceManager.GetString("DurationMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 mois.
        /// </summary>
        public static string DurationMonthZero {
            get {
                return ResourceManager.GetString("DurationMonthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # seconde.
        /// </summary>
        public static string DurationSecond {
            get {
                return ResourceManager.GetString("DurationSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # secondes.
        /// </summary>
        public static string DurationSecondPlural {
            get {
                return ResourceManager.GetString("DurationSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 seconde.
        /// </summary>
        public static string DurationSecondZero {
            get {
                return ResourceManager.GetString("DurationSecondZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # semaine.
        /// </summary>
        public static string DurationWeek {
            get {
                return ResourceManager.GetString("DurationWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # semaines.
        /// </summary>
        public static string DurationWeekPlural {
            get {
                return ResourceManager.GetString("DurationWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 semaine.
        /// </summary>
        public static string DurationWeekZero {
            get {
                return ResourceManager.GetString("DurationWeekZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # année.
        /// </summary>
        public static string DurationYear {
            get {
                return ResourceManager.GetString("DurationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ans.
        /// </summary>
        public static string DurationYearPlural {
            get {
                return ResourceManager.GetString("DurationYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 an.
        /// </summary>
        public static string DurationYearZero {
            get {
                return ResourceManager.GetString("DurationYearZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconde.
        /// </summary>
        public static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mois.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans {0}.
        /// </summary>
        public static string RelativeDateFuture {
            get {
                return ResourceManager.GetString("RelativeDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # jour.
        /// </summary>
        public static string RelativeDateFutureDay {
            get {
                return ResourceManager.GetString("RelativeDateFutureDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # jours.
        /// </summary>
        public static string RelativeDateFutureDayPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # heure.
        /// </summary>
        public static string RelativeDateFutureHour {
            get {
                return ResourceManager.GetString("RelativeDateFutureHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # heures.
        /// </summary>
        public static string RelativeDateFutureHourPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # milliseconde.
        /// </summary>
        public static string RelativeDateFutureMillisecond {
            get {
                return ResourceManager.GetString("RelativeDateFutureMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans #  millisecondes.
        /// </summary>
        public static string RelativeDateFutureMillisecondPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # minute.
        /// </summary>
        public static string RelativeDateFutureMinute {
            get {
                return ResourceManager.GetString("RelativeDateFutureMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # minutes.
        /// </summary>
        public static string RelativeDateFutureMinutePlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # mois.
        /// </summary>
        public static string RelativeDateFutureMonth {
            get {
                return ResourceManager.GetString("RelativeDateFutureMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # mois.
        /// </summary>
        public static string RelativeDateFutureMonthPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # seconde.
        /// </summary>
        public static string RelativeDateFutureSecond {
            get {
                return ResourceManager.GetString("RelativeDateFutureSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # secondes.
        /// </summary>
        public static string RelativeDateFutureSecondPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # semaine.
        /// </summary>
        public static string RelativeDateFutureWeek {
            get {
                return ResourceManager.GetString("RelativeDateFutureWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # semaines.
        /// </summary>
        public static string RelativeDateFutureWeekPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # an.
        /// </summary>
        public static string RelativeDateFutureYear {
            get {
                return ResourceManager.GetString("RelativeDateFutureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # ans.
        /// </summary>
        public static string RelativeDateFutureYearPlural {
            get {
                return ResourceManager.GetString("RelativeDateFutureYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jamais.
        /// </summary>
        public static string RelativeDateNever {
            get {
                return ResourceManager.GetString("RelativeDateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenant.
        /// </summary>
        public static string RelativeDateNow {
            get {
                return ResourceManager.GetString("RelativeDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a {0}.
        /// </summary>
        public static string RelativeDatePast {
            get {
                return ResourceManager.GetString("RelativeDatePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string RelativeDatePastDay {
            get {
                return ResourceManager.GetString("RelativeDatePastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # jours.
        /// </summary>
        public static string RelativeDatePastDayPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # heure.
        /// </summary>
        public static string RelativeDatePastHour {
            get {
                return ResourceManager.GetString("RelativeDatePastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # heures.
        /// </summary>
        public static string RelativeDatePastHourPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # milliseconde.
        /// </summary>
        public static string RelativeDatePastMillisecond {
            get {
                return ResourceManager.GetString("RelativeDatePastMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # millisecondes.
        /// </summary>
        public static string RelativeDatePastMillisecondPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # minute.
        /// </summary>
        public static string RelativeDatePastMinute {
            get {
                return ResourceManager.GetString("RelativeDatePastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # minutes.
        /// </summary>
        public static string RelativeDatePastMinutePlural {
            get {
                return ResourceManager.GetString("RelativeDatePastMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # mois.
        /// </summary>
        public static string RelativeDatePastMonth {
            get {
                return ResourceManager.GetString("RelativeDatePastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # mois.
        /// </summary>
        public static string RelativeDatePastMonthPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # seconde.
        /// </summary>
        public static string RelativeDatePastSecond {
            get {
                return ResourceManager.GetString("RelativeDatePastSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # secondes.
        /// </summary>
        public static string RelativeDatePastSecondPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # semaine.
        /// </summary>
        public static string RelativeDatePastWeek {
            get {
                return ResourceManager.GetString("RelativeDatePastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # semaines.
        /// </summary>
        public static string RelativeDatePastWeekPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # an.
        /// </summary>
        public static string RelativeDatePastYear {
            get {
                return ResourceManager.GetString("RelativeDatePastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # ans.
        /// </summary>
        public static string RelativeDatePastYearPlural {
            get {
                return ResourceManager.GetString("RelativeDatePastYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demain.
        /// </summary>
        public static string RelativeDateTomorrow {
            get {
                return ResourceManager.GetString("RelativeDateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string RelativeDateYesterday {
            get {
                return ResourceManager.GetString("RelativeDateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pas de temps.
        /// </summary>
        public static string RelativeDateZero {
            get {
                return ResourceManager.GetString("RelativeDateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconde.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
