//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Utilities.Geography.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Utilities.Geography.Extensions.CountryResources", typeof(CountryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Åland.
        /// </summary>
        public static string AlandIslands {
            get {
                return ResourceManager.GetString("AlandIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanie.
        /// </summary>
        public static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algérie.
        /// </summary>
        public static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa américaines.
        /// </summary>
        public static string AmericanSamoa {
            get {
                return ResourceManager.GetString("AmericanSamoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorre.
        /// </summary>
        public static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        public static string Angola {
            get {
                return ResourceManager.GetString("Angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anguilla.
        /// </summary>
        public static string Anguilla {
            get {
                return ResourceManager.GetString("Anguilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctique.
        /// </summary>
        public static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua-et-Barbuda.
        /// </summary>
        public static string AntiguaAndBarbuda {
            get {
                return ResourceManager.GetString("AntiguaAndBarbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine.
        /// </summary>
        public static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arménie.
        /// </summary>
        public static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        public static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australie.
        /// </summary>
        public static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autriche.
        /// </summary>
        public static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaïdjan.
        /// </summary>
        public static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        public static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahreïn.
        /// </summary>
        public static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        public static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbade.
        /// </summary>
        public static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biélorussie.
        /// </summary>
        public static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgique.
        /// </summary>
        public static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        public static string Belize {
            get {
                return ResourceManager.GetString("Belize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénin.
        /// </summary>
        public static string Benin {
            get {
                return ResourceManager.GetString("Benin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermudes.
        /// </summary>
        public static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhoutan.
        /// </summary>
        public static string Bhutan {
            get {
                return ResourceManager.GetString("Bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivie.
        /// </summary>
        public static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays-Bas caribéens.
        /// </summary>
        public static string Bonaire {
            get {
                return ResourceManager.GetString("Bonaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnie-Herzégovine.
        /// </summary>
        public static string BosniaAndHerzegovina {
            get {
                return ResourceManager.GetString("BosniaAndHerzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        public static string Botswana {
            get {
                return ResourceManager.GetString("Botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île Bouvet.
        /// </summary>
        public static string BouvetIsland {
            get {
                return ResourceManager.GetString("BouvetIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brésil.
        /// </summary>
        public static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territoire britannique de l&apos;océan Indien.
        /// </summary>
        public static string BritishIndianOceanTerritory {
            get {
                return ResourceManager.GetString("BritishIndianOceanTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei.
        /// </summary>
        public static string BruneiDarussalam {
            get {
                return ResourceManager.GetString("BruneiDarussalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarie.
        /// </summary>
        public static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        public static string BurkinaFaso {
            get {
                return ResourceManager.GetString("BurkinaFaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        public static string Burundi {
            get {
                return ResourceManager.GetString("Burundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap-Vert.
        /// </summary>
        public static string CaboVerde {
            get {
                return ResourceManager.GetString("CaboVerde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodge.
        /// </summary>
        public static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroun.
        /// </summary>
        public static string Cameroon {
            get {
                return ResourceManager.GetString("Cameroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Caïmans.
        /// </summary>
        public static string CaymanIslands {
            get {
                return ResourceManager.GetString("CaymanIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République centrafricaine.
        /// </summary>
        public static string CentralAfricanRepublic {
            get {
                return ResourceManager.GetString("CentralAfricanRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tchad.
        /// </summary>
        public static string Chad {
            get {
                return ResourceManager.GetString("Chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chili.
        /// </summary>
        public static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chine.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île Christmas.
        /// </summary>
        public static string ChristmasIsland {
            get {
                return ResourceManager.GetString("ChristmasIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Cocos.
        /// </summary>
        public static string CocosIslands {
            get {
                return ResourceManager.GetString("CocosIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombie.
        /// </summary>
        public static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comores.
        /// </summary>
        public static string Comoros {
            get {
                return ResourceManager.GetString("Comoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République du Congo.
        /// </summary>
        public static string Congo {
            get {
                return ResourceManager.GetString("Congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République démocratique du Congo.
        /// </summary>
        public static string CongoDemocraticRepublic {
            get {
                return ResourceManager.GetString("CongoDemocraticRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrique.
        /// </summary>
        public static string ContinentAfrica {
            get {
                return ResourceManager.GetString("ContinentAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctique.
        /// </summary>
        public static string ContinentAntarctica {
            get {
                return ResourceManager.GetString("ContinentAntarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asie.
        /// </summary>
        public static string ContinentAsia {
            get {
                return ResourceManager.GetString("ContinentAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string ContinentEurope {
            get {
                return ResourceManager.GetString("ContinentEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amérique du nord.
        /// </summary>
        public static string ContinentNorthAmerica {
            get {
                return ResourceManager.GetString("ContinentNorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Océanie.
        /// </summary>
        public static string ContinentOceania {
            get {
                return ResourceManager.GetString("ContinentOceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amérique du sud.
        /// </summary>
        public static string ContinentSouthAmerica {
            get {
                return ResourceManager.GetString("ContinentSouthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Cook.
        /// </summary>
        public static string CookIslands {
            get {
                return ResourceManager.GetString("CookIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        public static string CostaRica {
            get {
                return ResourceManager.GetString("CostaRica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côte d&apos;Ivoire.
        /// </summary>
        public static string CoteIvoire {
            get {
                return ResourceManager.GetString("CoteIvoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatie.
        /// </summary>
        public static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        public static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curaçao.
        /// </summary>
        public static string Curacao {
            get {
                return ResourceManager.GetString("Curacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chypre.
        /// </summary>
        public static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tchéquie.
        /// </summary>
        public static string Czechia {
            get {
                return ResourceManager.GetString("Czechia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danemark.
        /// </summary>
        public static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        public static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominique.
        /// </summary>
        public static string Dominica {
            get {
                return ResourceManager.GetString("Dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République dominicaine.
        /// </summary>
        public static string DominicanRepublic {
            get {
                return ResourceManager.GetString("DominicanRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équateur.
        /// </summary>
        public static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Égypte.
        /// </summary>
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvador.
        /// </summary>
        public static string ElSalvador {
            get {
                return ResourceManager.GetString("ElSalvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinée équatoriale.
        /// </summary>
        public static string EquatorialGuinea {
            get {
                return ResourceManager.GetString("EquatorialGuinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érythrée.
        /// </summary>
        public static string Eritrea {
            get {
                return ResourceManager.GetString("Eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonie.
        /// </summary>
        public static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eswatini.
        /// </summary>
        public static string Eswatini {
            get {
                return ResourceManager.GetString("Eswatini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éthiopie.
        /// </summary>
        public static string Ethiopia {
            get {
                return ResourceManager.GetString("Ethiopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malouines.
        /// </summary>
        public static string FalklandIslands {
            get {
                return ResourceManager.GetString("FalklandIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Féroé.
        /// </summary>
        public static string FaroeIslands {
            get {
                return ResourceManager.GetString("FaroeIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fidji.
        /// </summary>
        public static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finlande.
        /// </summary>
        public static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyane.
        /// </summary>
        public static string FrenchGuiana {
            get {
                return ResourceManager.GetString("FrenchGuiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynésie française.
        /// </summary>
        public static string FrenchPolynesia {
            get {
                return ResourceManager.GetString("FrenchPolynesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terres australes et antarctiques françaises.
        /// </summary>
        public static string FrenchSouthernTerritories {
            get {
                return ResourceManager.GetString("FrenchSouthernTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        public static string Gabon {
            get {
                return ResourceManager.GetString("Gabon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambie.
        /// </summary>
        public static string Gambia {
            get {
                return ResourceManager.GetString("Gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Géorgie.
        /// </summary>
        public static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allemagne.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        public static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        public static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grèce.
        /// </summary>
        public static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groenland.
        /// </summary>
        public static string Greenland {
            get {
                return ResourceManager.GetString("Greenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenade.
        /// </summary>
        public static string Grenada {
            get {
                return ResourceManager.GetString("Grenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadeloupe.
        /// </summary>
        public static string Guadeloupe {
            get {
                return ResourceManager.GetString("Guadeloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        public static string Guam {
            get {
                return ResourceManager.GetString("Guam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernesey.
        /// </summary>
        public static string Guernsey {
            get {
                return ResourceManager.GetString("Guernsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinée.
        /// </summary>
        public static string Guinea {
            get {
                return ResourceManager.GetString("Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinée-Bissau.
        /// </summary>
        public static string GuineaBissau {
            get {
                return ResourceManager.GetString("GuineaBissau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        public static string Guyana {
            get {
                return ResourceManager.GetString("Guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haïti.
        /// </summary>
        public static string Haiti {
            get {
                return ResourceManager.GetString("Haiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Heard-et-MacDonald.
        /// </summary>
        public static string HeardIslandAndMcdonaldIslands {
            get {
                return ResourceManager.GetString("HeardIslandAndMcdonaldIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Siège (État de la Cité du Vatican).
        /// </summary>
        public static string HolySee {
            get {
                return ResourceManager.GetString("HolySee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        public static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        public static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hongrie.
        /// </summary>
        public static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islande.
        /// </summary>
        public static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inde.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonésie.
        /// </summary>
        public static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        public static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irak.
        /// </summary>
        public static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irlande.
        /// </summary>
        public static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île de Man.
        /// </summary>
        public static string IsleOfMan {
            get {
                return ResourceManager.GetString("IsleOfMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israël.
        /// </summary>
        public static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italie.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaïque.
        /// </summary>
        public static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japon.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jersey.
        /// </summary>
        public static string Jersey {
            get {
                return ResourceManager.GetString("Jersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanie.
        /// </summary>
        public static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        public static string Kazakhstan {
            get {
                return ResourceManager.GetString("Kazakhstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        public static string Kenya {
            get {
                return ResourceManager.GetString("Kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        public static string Kiribati {
            get {
                return ResourceManager.GetString("Kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koweït.
        /// </summary>
        public static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirghizistan.
        /// </summary>
        public static string Kyrgyzstan {
            get {
                return ResourceManager.GetString("Kyrgyzstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laos.
        /// </summary>
        public static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettonie.
        /// </summary>
        public static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liban.
        /// </summary>
        public static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        public static string Lesotho {
            get {
                return ResourceManager.GetString("Lesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        public static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libye.
        /// </summary>
        public static string Libya {
            get {
                return ResourceManager.GetString("Libya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lituanie.
        /// </summary>
        public static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao.
        /// </summary>
        public static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        public static string Madagascar {
            get {
                return ResourceManager.GetString("Madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        public static string Malawi {
            get {
                return ResourceManager.GetString("Malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaisie.
        /// </summary>
        public static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        public static string Maldives {
            get {
                return ResourceManager.GetString("Maldives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        public static string Mali {
            get {
                return ResourceManager.GetString("Mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malte.
        /// </summary>
        public static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Marshall.
        /// </summary>
        public static string MarshallIslands {
            get {
                return ResourceManager.GetString("MarshallIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martinique.
        /// </summary>
        public static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritanie.
        /// </summary>
        public static string Mauritania {
            get {
                return ResourceManager.GetString("Mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maurice.
        /// </summary>
        public static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayotte.
        /// </summary>
        public static string Mayotte {
            get {
                return ResourceManager.GetString("Mayotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexique.
        /// </summary>
        public static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to États fédérés de Micronésie.
        /// </summary>
        public static string Micronesia {
            get {
                return ResourceManager.GetString("Micronesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldavie.
        /// </summary>
        public static string Moldova {
            get {
                return ResourceManager.GetString("Moldova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolie.
        /// </summary>
        public static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monténégro.
        /// </summary>
        public static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montserrat.
        /// </summary>
        public static string Montserrat {
            get {
                return ResourceManager.GetString("Montserrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroc.
        /// </summary>
        public static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        public static string Mozambique {
            get {
                return ResourceManager.GetString("Mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birmanie.
        /// </summary>
        public static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibie.
        /// </summary>
        public static string Namibia {
            get {
                return ResourceManager.GetString("Namibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        public static string Nauru {
            get {
                return ResourceManager.GetString("Nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Népal.
        /// </summary>
        public static string Nepal {
            get {
                return ResourceManager.GetString("Nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays-Bas.
        /// </summary>
        public static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle-Calédonie.
        /// </summary>
        public static string NewCaledonia {
            get {
                return ResourceManager.GetString("NewCaledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle-Zélande.
        /// </summary>
        public static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        public static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        public static string Niger {
            get {
                return ResourceManager.GetString("Niger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        public static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niue.
        /// </summary>
        public static string Niue {
            get {
                return ResourceManager.GetString("Niue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île Norfolk.
        /// </summary>
        public static string NorfolkIsland {
            get {
                return ResourceManager.GetString("NorfolkIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Mariannes du Nord.
        /// </summary>
        public static string NorthernMarianaIslands {
            get {
                return ResourceManager.GetString("NorthernMarianaIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corée du Nord.
        /// </summary>
        public static string NorthKorea {
            get {
                return ResourceManager.GetString("NorthKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macédoine du Nord.
        /// </summary>
        public static string NorthMacedonia {
            get {
                return ResourceManager.GetString("NorthMacedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norvège.
        /// </summary>
        public static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        public static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        public static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaos.
        /// </summary>
        public static string Palau {
            get {
                return ResourceManager.GetString("Palau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine.
        /// </summary>
        public static string Palestine {
            get {
                return ResourceManager.GetString("Palestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        public static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papouasie-Nouvelle-Guinée.
        /// </summary>
        public static string PapuaNewGuinea {
            get {
                return ResourceManager.GetString("PapuaNewGuinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        public static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pérou.
        /// </summary>
        public static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        public static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Pitcairn.
        /// </summary>
        public static string Pitcairn {
            get {
                return ResourceManager.GetString("Pitcairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pologne.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porto Rico.
        /// </summary>
        public static string PuertoRico {
            get {
                return ResourceManager.GetString("PuertoRico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        public static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Réunion.
        /// </summary>
        public static string Reunion {
            get {
                return ResourceManager.GetString("Reunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roumanie.
        /// </summary>
        public static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russie.
        /// </summary>
        public static string RussianFederation {
            get {
                return ResourceManager.GetString("RussianFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        public static string Rwanda {
            get {
                return ResourceManager.GetString("Rwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Barthélemy.
        /// </summary>
        public static string SaintBartheLemy {
            get {
                return ResourceManager.GetString("SaintBartheLemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sainte-Hélène, Ascension et Tristan da Cunha.
        /// </summary>
        public static string SaintHelena {
            get {
                return ResourceManager.GetString("SaintHelena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Christophe-et-Niévès.
        /// </summary>
        public static string SaintKittsAndNevis {
            get {
                return ResourceManager.GetString("SaintKittsAndNevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sainte-Lucie.
        /// </summary>
        public static string SaintLucia {
            get {
                return ResourceManager.GetString("SaintLucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Martin.
        /// </summary>
        public static string SaintMartin {
            get {
                return ResourceManager.GetString("SaintMartin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Pierre-et-Miquelon.
        /// </summary>
        public static string SaintPierreAndMiquelon {
            get {
                return ResourceManager.GetString("SaintPierreAndMiquelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Vincent-et-les-Grenadines.
        /// </summary>
        public static string SaintVincentAndTheGrenadines {
            get {
                return ResourceManager.GetString("SaintVincentAndTheGrenadines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        public static string Samoa {
            get {
                return ResourceManager.GetString("Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Marin.
        /// </summary>
        public static string SanMarino {
            get {
                return ResourceManager.GetString("SanMarino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tomé-et-Principe.
        /// </summary>
        public static string SaoTomeAndPrincipe {
            get {
                return ResourceManager.GetString("SaoTomeAndPrincipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabie saoudite.
        /// </summary>
        public static string SaudiArabia {
            get {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sénégal.
        /// </summary>
        public static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbie.
        /// </summary>
        public static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        public static string Seychelles {
            get {
                return ResourceManager.GetString("Seychelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        public static string SierraLeone {
            get {
                return ResourceManager.GetString("SierraLeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapour.
        /// </summary>
        public static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint-Martin.
        /// </summary>
        public static string SintMaarten {
            get {
                return ResourceManager.GetString("SintMaarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovaquie.
        /// </summary>
        public static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovénie.
        /// </summary>
        public static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salomon.
        /// </summary>
        public static string SolomonIslands {
            get {
                return ResourceManager.GetString("SolomonIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalie.
        /// </summary>
        public static string Somalia {
            get {
                return ResourceManager.GetString("Somalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrique du Sud.
        /// </summary>
        public static string SouthAfrica {
            get {
                return ResourceManager.GetString("SouthAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Géorgie du Sud-et-les îles Sandwich du Sud.
        /// </summary>
        public static string SouthGeorgiaAndTheSouthSandwichIslands {
            get {
                return ResourceManager.GetString("SouthGeorgiaAndTheSouthSandwichIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corée du Sud.
        /// </summary>
        public static string SouthKorea {
            get {
                return ResourceManager.GetString("SouthKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soudan du Sud.
        /// </summary>
        public static string SouthSudan {
            get {
                return ResourceManager.GetString("SouthSudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espagne.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        public static string SriLanka {
            get {
                return ResourceManager.GetString("SriLanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soudan.
        /// </summary>
        public static string Sudan {
            get {
                return ResourceManager.GetString("Sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        public static string Suriname {
            get {
                return ResourceManager.GetString("Suriname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svalbard et ile Jan Mayen.
        /// </summary>
        public static string SvalbardAndJanMayen {
            get {
                return ResourceManager.GetString("SvalbardAndJanMayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suède.
        /// </summary>
        public static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suisse.
        /// </summary>
        public static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrie.
        /// </summary>
        public static string SyrianArabRepublic {
            get {
                return ResourceManager.GetString("SyrianArabRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taïwan.
        /// </summary>
        public static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tadjikistan.
        /// </summary>
        public static string Tajikistan {
            get {
                return ResourceManager.GetString("Tajikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzanie.
        /// </summary>
        public static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaïlande.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor oriental.
        /// </summary>
        public static string TimorLeste {
            get {
                return ResourceManager.GetString("TimorLeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        public static string Togo {
            get {
                return ResourceManager.GetString("Togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokelau.
        /// </summary>
        public static string Tokelau {
            get {
                return ResourceManager.GetString("Tokelau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        public static string Tonga {
            get {
                return ResourceManager.GetString("Tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinité-et-Tobago.
        /// </summary>
        public static string TrinidadAndTobago {
            get {
                return ResourceManager.GetString("TrinidadAndTobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisie.
        /// </summary>
        public static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquie.
        /// </summary>
        public static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkménistan.
        /// </summary>
        public static string Turkmenistan {
            get {
                return ResourceManager.GetString("Turkmenistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Turques-et-Caïques.
        /// </summary>
        public static string TurksAndCaicosIslands {
            get {
                return ResourceManager.GetString("TurksAndCaicosIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvalu.
        /// </summary>
        public static string Tuvalu {
            get {
                return ResourceManager.GetString("Tuvalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouganda.
        /// </summary>
        public static string Uganda {
            get {
                return ResourceManager.GetString("Uganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Émirats arabes unis.
        /// </summary>
        public static string UnitedArabEmirates {
            get {
                return ResourceManager.GetString("UnitedArabEmirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royaume-Uni.
        /// </summary>
        public static string UnitedKingdomOfGreatBritainAndNorthernIreland {
            get {
                return ResourceManager.GetString("UnitedKingdomOfGreatBritainAndNorthernIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles mineures éloignées des États-Unis.
        /// </summary>
        public static string UnitedStatesMinorOutlyingIslands {
            get {
                return ResourceManager.GetString("UnitedStatesMinorOutlyingIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to États-Unis.
        /// </summary>
        public static string UnitedStatesOfAmerica {
            get {
                return ResourceManager.GetString("UnitedStatesOfAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        public static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouzbékistan.
        /// </summary>
        public static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        public static string Vanuatu {
            get {
                return ResourceManager.GetString("Vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        public static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viêt Nam.
        /// </summary>
        public static string VietNam {
            get {
                return ResourceManager.GetString("VietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Vierges britanniques.
        /// </summary>
        public static string VirginIslandsUK {
            get {
                return ResourceManager.GetString("VirginIslandsUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Îles Vierges des États-Unis.
        /// </summary>
        public static string VirginIslandsUS {
            get {
                return ResourceManager.GetString("VirginIslandsUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallis-et-Futuna.
        /// </summary>
        public static string WallisAndFutuna {
            get {
                return ResourceManager.GetString("WallisAndFutuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République arabe sahraouie démocratique.
        /// </summary>
        public static string WesternSahara {
            get {
                return ResourceManager.GetString("WesternSahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yémen.
        /// </summary>
        public static string Yemen {
            get {
                return ResourceManager.GetString("Yemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambie.
        /// </summary>
        public static string Zambia {
            get {
                return ResourceManager.GetString("Zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        public static string Zimbabwe {
            get {
                return ResourceManager.GetString("Zimbabwe", resourceCulture);
            }
        }
    }
}
