// -----------------------------------------------------------------------
// <copyright file="Inflectors.English.cs" company="Stéphane ANDRE">
// Copyright (c) Stéphane ANDRE. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using MyNet.Globalization.Culture;

namespace MyNet.Globalization.Inflection.Cultures;

public static partial class Inflectors
{
    /// <summary>
    /// Gets an inflector for the English language, which includes rules for pluralization and singularization of English nouns, as well as handling irregular forms and uncountable nouns. This inflector can be used to convert between singular and plural forms of English words based on a comprehensive set of linguistic rules and exceptions specific to the English language.
    /// </summary>
    public static IInflector English { get; } = Inflector.Create(SupportedCultures.English)
        .AddPluralRule("$", "s")
        .AddPluralRule("s$", "s")
        .AddPluralRule("(ax|test)is$", "$1es")
        .AddPluralRule("(octop|vir|alumn|fung|cact|foc|hippopotam|radi|stimul|syllab|nucle)us$", "$1i")
        .AddPluralRule("(alias|bias|iris|status|campus|apparatus|virus|walrus|trellis)$", "$1es")
        .AddPluralRule("(buffal|tomat|volcan|ech|embarg|her|mosquit|potat|torped|vet)o$", "$1oes")
        .AddPluralRule("([dti])um$", "$1a")
        .AddPluralRule("sis$", "ses")
        .AddPluralRule("(?:([^f])fe|([lr])f)$", "$1$2ves")
        .AddPluralRule("(hive)$", "$1s")
        .AddPluralRule("([^aeiouy]|qu)y$", "$1ies")
        .AddPluralRule("(x|ch|ss|sh)$", "$1es")
        .AddPluralRule("(matr|vert|ind|d)ix|ex$", "$1ices")
        .AddPluralRule("(^[m|l])ouse$", "$1ice")
        .AddPluralRule("^(ox)$", "$1en")
        .AddPluralRule("(quiz)$", "$1zes")
        .AddPluralRule("(buz|blit|walt)z$", "$1zes")
        .AddPluralRule("(hoo|lea|loa|thie)f$", "$1ves")
        .AddPluralRule("(alumn|alg|larv|vertebr)a$", "$1ae")
        .AddPluralRule("(criteri|phenomen)on$", "$1a")
        .AddSingularRule("s$", string.Empty)
        .AddSingularRule("(n)ews$", "$1ews")
        .AddSingularRule("([dti])a$", "$1um")
        .AddSingularRule("(analy|ba|diagno|parenthe|progno|synop|the|ellip|empha|neuro|oa|paraly)ses$", "$1sis")
        .AddSingularRule("([^f])ves$", "$1fe")
        .AddSingularRule("(hive)s$", "$1")
        .AddSingularRule("(tive)s$", "$1")
        .AddSingularRule("([lr]|hoo|lea|loa|thie)ves$", "$1f")
        .AddSingularRule("(^zomb)?([^aeiouy]|qu)ies$", "$2y")
        .AddSingularRule("(s)eries$", "$1eries")
        .AddSingularRule("(m)ovies$", "$1ovie")
        .AddSingularRule("(x|ch|ss|sh)es$", "$1")
        .AddSingularRule("(^[m|l])ice$", "$1ouse")
        .AddSingularRule("(o)es$", "$1")
        .AddSingularRule("(shoe)s$", "$1")
        .AddSingularRule("(cris|ax|test)es$", "$1is")
        .AddSingularRule("(octop|vir|alumn|fung|cact|foc|hippopotam|radi|stimul|syllab|nucle)i$", "$1us")
        .AddSingularRule("(alias|bias|iris|status|campus|apparatus|virus|walrus|trellis)es$", "$1")
        .AddSingularRule("^(ox)en", "$1")
        .AddSingularRule("(matr|d)ices$", "$1ix")
        .AddSingularRule("(vert|ind)ices$", "$1ex")
        .AddSingularRule("(quiz)zes$", "$1")
        .AddSingularRule("(buz|blit|walt)zes$", "$1z")
        .AddSingularRule("(alumn|alg|larv|vertebr)ae$", "$1a")
        .AddSingularRule("(criteri|phenomen)a$", "$1on")
        .AddSingularRule("([b|r|c]ook|room|smooth)ies$", "$1ie")
        .AddIrregular("person", "people")
        .AddIrregular("man", "men")
        .AddIrregular("human", "humans")
        .AddIrregular("child", "children")
        .AddIrregular("sex", "sexes")
        .AddIrregular("move", "moves")
        .AddIrregular("goose", "geese")
        .AddIrregular("wave", "waves")
        .AddIrregular("die", "dice")
        .AddIrregular("foot", "feet")
        .AddIrregular("tooth", "teeth")
        .AddIrregular("curriculum", "curricula")
        .AddIrregular("database", "databases")
        .AddIrregular("zombie", "zombies")
        .AddIrregular("personnel", "personnel")
        .AddIrregular("cache", "caches")
        .AddIrregular("is", "are", matchEnding: false)
        .AddIrregular("that", "those", matchEnding: false)
        .AddIrregular("this", "these", matchEnding: false)
        .AddIrregular("bus", "buses", matchEnding: false)
        .AddIrregular("staff", "staff", matchEnding: false)
        .AddUncountable("equipment")
        .AddUncountable("information")
        .AddUncountable("corn")
        .AddUncountable("milk")
        .AddUncountable("rice")
        .AddUncountable("money")
        .AddUncountable("species")
        .AddUncountable("series")
        .AddUncountable("fish")
        .AddUncountable("sheep")
        .AddUncountable("deer")
        .AddUncountable("aircraft")
        .AddUncountable("oz")
        .AddUncountable("tsp")
        .AddUncountable("tbsp")
        .AddUncountable("ml")
        .AddUncountable("l")
        .AddUncountable("water")
        .AddUncountable("waters")
        .AddUncountable("semen")
        .AddUncountable("sperm")
        .AddUncountable("bison")
        .AddUncountable("grass")
        .AddUncountable("hair")
        .AddUncountable("mud")
        .AddUncountable("elk")
        .AddUncountable("luggage")
        .AddUncountable("moose")
        .AddUncountable("offspring")
        .AddUncountable("salmon")
        .AddUncountable("shrimp")
        .AddUncountable("someone")
        .AddUncountable("swine")
        .AddUncountable("trout")
        .AddUncountable("tuna")
        .AddUncountable("corps")
        .AddUncountable("scissors")
        .AddUncountable("means")
        .AddUncountable("mail")
        .AddUncountable("data")
        .Build();
}
