//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Fakers.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Fakers.Localization.AddressResources", typeof(AddressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paris;Marseille;Lyon;Toulouse;Nice;Nantes;Montpellier;Strasbourg;Bordeaux;Lille;Rennes;Reims;Toulon;Saint-Étienne;Le Havre;Dijon;Grenoble;Angers;Villeurbanne;Saint-Denis;Nîmes;Clermont-Ferrand;Aix-en-Provence;Le Mans;Brest;Tours;Amiens;Annecy;Limoges;Boulogne-Billancourt;Metz;Besançon;Perpignan;Orléans;Rouen;Saint-Denis;Montreuil;Argenteuil;Mulhouse;Caen;Nancy;Saint-Paul;Tourcoing;Roubaix;Nanterre;Vitry-sur-Seine;Nouméa;Créteil;Avignon;Poitiers;Aubervilliers;Asnières-sur-Seine;Colombes;Dunkerque;Aulnay-sous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####.
        /// </summary>
        internal static string PostalCodeFormats {
            get {
                return ResourceManager.GetString("PostalCodeFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Number} {Type} {Name};{Number} {Suffix} {Type} {Name}.
        /// </summary>
        internal static string StreetFormats {
            get {
                return ResourceManager.GetString("StreetFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de la Paix;Victor Hugo;Jean Jaurès;du Général de Gaulle;des Écoles;de la République;des Lilas;des Roses;de Verdun;Pasteur;du Moulin;des Acacias;de la Gare;des Tilleuls;de Bretagne;de Provence;de Paris;des Vignes;du Château;de l&apos;Église;des Jardins;des Peupliers;des Bleuets;de la Liberté;des Champs;de la Fontaine.
        /// </summary>
        internal static string StreetNames {
            get {
                return ResourceManager.GetString("StreetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis;ter;quater.
        /// </summary>
        internal static string StreetSuffixes {
            get {
                return ResourceManager.GetString("StreetSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rue;avenue;boulevard;impasse;allée;chemin;place;route;quai;cours;faubourg;passage;square;voie;villa;esplanade;promenade;rocade;sentier;ruelle.
        /// </summary>
        internal static string StreetTypes {
            get {
                return ResourceManager.GetString("StreetTypes", resourceCulture);
            }
        }
    }
}
