//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------
#nullable enable

namespace MyNet.Observable.Localization;
using System.ComponentModel;
using System.Globalization;
using System.Resources;

public class ValidationResources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal ValidationResources()
    {
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new ResourceManager("MyNet.Observable.Localization.ValidationResources", typeof(ValidationResources).Assembly);
            return resourceMan;
        }
    }

    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public static CultureInfo Culture
    {
        get => resourceCulture ?? CultureInfo.CurrentUICulture;
        set => resourceCulture = value;
    }

    public static string CollectionDuplicateItems => ResourceManager.GetString("CollectionDuplicateItems", resourceCulture) ?? string.Empty;
    public static string CollectionRequiresAtLeastOneItem => ResourceManager.GetString("CollectionRequiresAtLeastOneItem", resourceCulture) ?? string.Empty;
    public static string FieldExceedsMaxLength => ResourceManager.GetString("FieldExceedsMaxLength", resourceCulture) ?? string.Empty;
    public static string FieldFileNotFound => ResourceManager.GetString("FieldFileNotFound", resourceCulture) ?? string.Empty;
    public static string FieldInvalidEmail => ResourceManager.GetString("FieldInvalidEmail", resourceCulture) ?? string.Empty;
    public static string FieldInvalidFilePath => ResourceManager.GetString("FieldInvalidFilePath", resourceCulture) ?? string.Empty;
    public static string FieldInvalidPhoneNumber => ResourceManager.GetString("FieldInvalidPhoneNumber", resourceCulture) ?? string.Empty;
    public static string FieldIsRequired => ResourceManager.GetString("FieldIsRequired", resourceCulture) ?? string.Empty;
    public static string FieldMustBeBetween => ResourceManager.GetString("FieldMustBeBetween", resourceCulture) ?? string.Empty;
    public static string FieldMustBeGreaterThan => ResourceManager.GetString("FieldMustBeGreaterThan", resourceCulture) ?? string.Empty;
    public static string FieldMustBeGreaterThanOrEqualTo => ResourceManager.GetString("FieldMustBeGreaterThanOrEqualTo", resourceCulture) ?? string.Empty;
    public static string FieldMustBeInPast => ResourceManager.GetString("FieldMustBeInPast", resourceCulture) ?? string.Empty;
    public static string FieldMustBeLessThan => ResourceManager.GetString("FieldMustBeLessThan", resourceCulture) ?? string.Empty;
    public static string FieldMustBeLessThanOrEqualTo => ResourceManager.GetString("FieldMustBeLessThanOrEqualTo", resourceCulture) ?? string.Empty;
    public static string PathPartNotFound => ResourceManager.GetString("PathPartNotFound", resourceCulture) ?? string.Empty;
}
