name: Deploy Avalonia Browser Demo to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      - name: Install workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload restore

      - name: Publish Avalonia Browser demo
        run: |
          echo "🌐 Publishing Avalonia Browser demo..."
          
          if [ -f "demos/MyNet.Avalonia.Demo.Browser/MyNet.Avalonia.Demo.Browser.csproj" ]; then
            echo "📦 Publishing Browser demo..."
            dotnet publish "demos/MyNet.Avalonia.Demo.Browser/MyNet.Avalonia.Demo.Browser.csproj" \
              --configuration Release \
              --output publish/browser \
              -f net10.0-browser
            
            # Prepare GitHub Pages content
            mkdir -p pages/app
            cp -r publish/browser/wwwroot/* pages/app/
            
            echo "✅ GitHub Pages content prepared"
          else
            echo "❌ Browser demo project not found"
            exit 1
          fi

      - name: Create landing page
        run: |
          cat > pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="utf-8">
              <title>MyNet Avalonia Browser Demo</title>
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <style>
                  body { 
                      margin: 0; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px 20px;
                  }
                  .container { max-width: 600px; margin: 0 auto; }
                  .demo-button {
                      display: inline-block;
                      padding: 15px 30px;
                      background: rgba(255,255,255,0.2);
                      border: 2px solid white;
                      color: white;
                      text-decoration: none;
                      border-radius: 10px;
                      margin: 20px;
                      transition: all 0.3s ease;
                  }
                  .demo-button:hover { background: rgba(255,255,255,0.3); }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 MyNet Avalonia Demo</h1>
                  <p>Cross-platform demo application powered by .NET WebAssembly</p>
                  <a href="./app/" class="demo-button">🌐 Launch Demo Application</a>
                  <p><small>Built with Avalonia UI and .NET WebAssembly</small></p>
              </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display deployment info
        run: |
          echo "🎉 Deployment completed!"
          echo "📄 Site URL: ${{ steps.deployment.outputs.page_url }}"
          echo "📦 Demo URL: ${{ steps.deployment.outputs.page_url }}app/"
